### ISSUE TITLE
部署guns-lite的几个问题记录如下

### ISSUE THREAD

**Issue by burnszp** [enilu/guns-lite#3]
1、我的mysql版本是：mysql-5.7.18-winx64，在创建数据库guns-lite，报错，`mysql> create database guns-lite;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-lite' at line 1`，所以暂时改用guns_lite创建数据库实例了。
2、由于我把数据库实例由guns-lite变为guns_lite，所以原以为改个guns-dao模块下的src/test/resources下的application-test.properties中的配置就够了，结果在运行guns-admin模块下的类cn.enilu.guns.admin.AdminApplication,报连接guns-lite的错误，我改了啊？？才发现guns-admin模块下src/main/resources下几个配置文件也都有mysql的配置信息，逐个改完之后，继续启动才启动正常没报错。
3、根据readme.md的说法运行https://localhost:8080，结果页面没刷新出来想要的界面，一看后台报错了:`2018-5-22 16:50:11 [main] INFO [AdminApplication]:47 AdminApplication is success!
2018-5-22 16:50:46 [http-nio-8080-exec-1] INFO [Http11Processor]:181 Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:421)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:667)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
2018-5-22 16:50:46 [http-nio-8080-exec-2] INFO [Http11Processor]:181 Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.`
看了大概意思是http和https的使用错误吧，就改为http://localhost:8080，才能正常访问。

不知上述有哪些步骤或操作有问题或可以优化的？

**Comment by burnszp** [comment]
这个mysql我也是用source guns-lite.sql，结果报错，一条一条执行就没问题，心塞喽了
mysql> select database();
+------------+
| database() |
+------------+
| guns_lite  |
+------------+
1 row in set (0.00 sec)

mysql> source C:\Users\Administrator\Downloads\guns-lite-master\guns-admin\sql\guns-lite.sql
ERROR:
Unknown command '\U'.
ERROR:
Unknown command '\A'.
ERROR:
Unknown command '\D'.
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'source C:\Users\Administrator\Downloads' at line 1
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uns-lite-master' at line 1
--------------
mysql  Ver 14.14 Distrib 5.7.18, for Win64 (x86_64)

Connection id:          3
Current database:       guns_lite
Current user:           root@localhost
SSL:                    Not in use
Using delimiter:        ;
Server version:         5.7.18 MySQL Community Server (GPL)
Protocol version:       10
Connection:             localhost via TCP/IP
Server characterset:    utf8
Db     characterset:    utf8
Client characterset:    utf8
Conn.  characterset:    utf8
TCP port:               3306
Uptime:                 8 min 55 sec

Threads: 1  Questions: 20  Slow queries: 0  Opens: 105  Flush tables: 1  Open tables: 98  Queries per second avg: 0.037
--------------

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'uns-adminql' at line 1
    -> ^C

后来楼主推荐用navicat连mysql和oracle进行操作的没遇到什么问题工具效率高
